- name: nyomo.mysql57
  src: https://github.com/nyomo/ansible-role-mysql57.git
- name: nyomo.rbenv
  src: https://github.com/nyomo/ansible-role-rbenv.git
- name: nyomo.apache_passsenger
  src: https://github.com/nyomo/ansible-role-apache_passenger.git
