---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: redmine_docker
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
vars:
  - docker_httpd_external_port: 8081
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
